// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces/eventHandler.go
//
// Generated by this command:
//
//	mockgen -source=./interfaces/eventHandler.go -destination=./mocks/eventHandler_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
