---
seer:
  logLevel: "info"
node:
  rpc:
    maxConnections: 25
    urls:
      - "http://localhost:8545" #point to an archive node for historical sync

  ws:
    maxConnections: 5
    urls:
      - "ws://localhost:8546" #point to an archive node for historical sync
  sync:
    history: true
db:
  url: "http://127.0.0.1:8086"
  # yamllint disable-line rule:line-length
  token: "${INFLUXDB_TOKEN}"
  bucket: "mainnet"
  org: "autonity"
  createBucket: true
abi:
  dir: "../abis"
...
