---
seer:
  logLevel: "info"
node:
  rpc:
    maxConnections: 25
    urls:
      - "https://rpc2.mainnet.autonity.org"

  ws:
    maxConnections: 5
    urls:
      - "wss://rpc2.mainnet.autonity.org/ws"
        # - "wss://rpc-internal-1.piccadilly.autonity.org/ws"
  sync:
    history: true
db:
  url: "http://127.0.0.1:8086"
  # yamllint disable-line rule:line-length
  token: "51uslKJjS7prMkfmNZVWyPon71vP43dlI4yD_Jws01g-sDkV5fRCj4CPAxaZvl13qU6BueAlTtJ0nQKLUbByUA=="
  bucket: "mainnet"
  org: "autonity"
  createBucket: true
abi:
  dir: "../abis"
...
