---
seer:
  logLevel: "info"
node:
  rpc:
    maxConnections: 25
    urls:
      - "https://rpc2.mainnet.autonity.org"

  ws:
    maxConnections: 5
    urls:
      - "wss://rpc2.mainnet.autonity.org/ws"
  sync:
    history: true
db:
  url: "http://127.0.0.1:8086"
  # yamllint disable-line rule:line-length
  token: "${INFLUXDB_TOKEN}"
  bucket: "mainnet"
  org: "autonity"
  createBucket: true
abi:
  dir: "../abis"
...
