---
seer:
  logLevel: "info"
node:
  rpc:
    maxConnections: 25
    urls:
      - "http://35.242.168.170:8545"
  ws:
    maxConnections: 5
    urls:
      - "wss://rpc2.piccadilly.autonity.org/ws"
  sync:
    history: true  # options last, latest or genesis
db:
  url: "http://127.0.0.1:8086"
  # yamllint disable-line rule:line-length
  token: "eHSHkn4oF2t5W8HeB8OSdoM5MvokeVypG6gdmEx4oIYc5hP3w2mISDU3GrQDdDLkhYQxFW0nzg6xtB2m6q0ZJA=="
  bucket: "seer_temp_1"
  org: "autonity"
abi:
  dir: "../abis"
...
