apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: influxdb-mainnet
    isDefault: true
    jsonData:
      version: Flux
      organization: autonity
      defaultBucket: mainnet
      maxSeries: 1000
    secureJsonData:
      token: "${INFLUXDB_TOKEN}"
    editable: true
